// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

// Import user types
import { TxtDefType } from "./../common.sol";

ResourceId constant _tableId = ResourceId.wrap(
  bytes32(abi.encodePacked(RESOURCE_TABLE, bytes14("meat"), bytes16("TextDefStore")))
);
ResourceId constant TextDefStoreTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x0004010104000000000000000000000000000000000000000000000000000000
);

struct TextDefStoreData {
  uint32 owner;
  string value;
}

library TextDefStore {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.BYTES32;
    _keySchema[1] = SchemaType.UINT8;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](2);
    _valueSchema[0] = SchemaType.UINT32;
    _valueSchema[1] = SchemaType.STRING;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "texDefId";
    keyNames[1] = "texDefType";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "owner";
    fieldNames[1] = "value";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get owner.
   */
  function getOwner(bytes32 texDefId, TxtDefType texDefType) internal view returns (uint32 owner) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get owner.
   */
  function _getOwner(bytes32 texDefId, TxtDefType texDefType) internal view returns (uint32 owner) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set owner.
   */
  function setOwner(bytes32 texDefId, TxtDefType texDefType, uint32 owner) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((owner)), _fieldLayout);
  }

  /**
   * @notice Set owner.
   */
  function _setOwner(bytes32 texDefId, TxtDefType texDefType, uint32 owner) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((owner)), _fieldLayout);
  }

  /**
   * @notice Get value.
   */
  function getValue(bytes32 texDefId, TxtDefType texDefType) internal view returns (string memory value) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get value.
   */
  function _getValue(bytes32 texDefId, TxtDefType texDefType) internal view returns (string memory value) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set value.
   */
  function setValue(bytes32 texDefId, TxtDefType texDefType, string memory value) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((value)));
  }

  /**
   * @notice Set value.
   */
  function _setValue(bytes32 texDefId, TxtDefType texDefType, string memory value) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((value)));
  }

  /**
   * @notice Get the length of value.
   */
  function lengthValue(bytes32 texDefId, TxtDefType texDefType) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of value.
   */
  function _lengthValue(bytes32 texDefId, TxtDefType texDefType) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of value.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemValue(bytes32 texDefId, TxtDefType texDefType, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of value.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemValue(
    bytes32 texDefId,
    TxtDefType texDefType,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to value.
   */
  function pushValue(bytes32 texDefId, TxtDefType texDefType, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to value.
   */
  function _pushValue(bytes32 texDefId, TxtDefType texDefType, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from value.
   */
  function popValue(bytes32 texDefId, TxtDefType texDefType) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from value.
   */
  function _popValue(bytes32 texDefId, TxtDefType texDefType) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of value at `_index`.
   */
  function updateValue(bytes32 texDefId, TxtDefType texDefType, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of value at `_index`.
   */
  function _updateValue(bytes32 texDefId, TxtDefType texDefType, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 texDefId, TxtDefType texDefType) internal view returns (TextDefStoreData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 texDefId, TxtDefType texDefType) internal view returns (TextDefStoreData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 texDefId, TxtDefType texDefType, uint32 owner, string memory value) internal {
    bytes memory _staticData = encodeStatic(owner);

    PackedCounter _encodedLengths = encodeLengths(value);
    bytes memory _dynamicData = encodeDynamic(value);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 texDefId, TxtDefType texDefType, uint32 owner, string memory value) internal {
    bytes memory _staticData = encodeStatic(owner);

    PackedCounter _encodedLengths = encodeLengths(value);
    bytes memory _dynamicData = encodeDynamic(value);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 texDefId, TxtDefType texDefType, TextDefStoreData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.owner);

    PackedCounter _encodedLengths = encodeLengths(_table.value);
    bytes memory _dynamicData = encodeDynamic(_table.value);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 texDefId, TxtDefType texDefType, TextDefStoreData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.owner);

    PackedCounter _encodedLengths = encodeLengths(_table.value);
    bytes memory _dynamicData = encodeDynamic(_table.value);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint32 owner) {
    owner = (uint32(Bytes.slice4(_blob, 0)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    PackedCounter _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory value) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    value = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    PackedCounter _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (TextDefStoreData memory _table) {
    (_table.owner) = decodeStatic(_staticData);

    (_table.value) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 texDefId, TxtDefType texDefType) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 texDefId, TxtDefType texDefType) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint32 owner) internal pure returns (bytes memory) {
    return abi.encodePacked(owner);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory value) internal pure returns (PackedCounter _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = PackedCounterLib.pack(bytes(value).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory value) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((value)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dyanmic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(uint32 owner, string memory value) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(owner);

    PackedCounter _encodedLengths = encodeLengths(value);
    bytes memory _dynamicData = encodeDynamic(value);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 texDefId, TxtDefType texDefType) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = texDefId;
    _keyTuple[1] = bytes32(uint256(uint8(texDefType)));

    return _keyTuple;
  }
}
