// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum TypeKeys {
  None,
  BiomeTypes,
  TerrainTypes,
  RoomType,
  ActionType
}

enum BiomeType {
  None,
  Tundra,
  Arctic,
  Temporate,
  Alpine,
  Jungle,
  Faery
}

enum TerrainType {
  None,
  Path,
  Forest,
  Plains,
  Mud,
  DirtPath,
  Portal
}

enum RoomType {
  None,
  WoodCabin,
  Store,
  Cavern,
  StoneCabin,
  Fort
}

enum DirectionType {
  None,
  North,
  South,
  East,
  West,
  Up,
  Down,
  Forward,
  Backwards
}

enum DirObjectType {
  None,
  Door,
  Window,
  Stairs,
  Ladder
}

enum ActionType {
  None,
  Go,
  Move,
  Loot,
  Describe,
  Take,
  Kick,
  Lock,
  Unlock,
  Open,
  Look
}

enum ObjectType {
  None,
  Football,
  Key,
  Knife,
  Bottle
}

enum GrammarType {
  None,
  DefiniteArticle,
  Preposition
}

enum MaterialType {
  None,
  Wood,
  Stone,
  Iron,
  Shit,
  IKEA,
  Flesh
}

enum TexDefType {
  None,
  Door,
  WoodCabin,
  DirtPath
}

enum CommandError {
  NONE,
  LEN,
  NOP,
  GONOWHERE,
  GOWHERE
}
