// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum RoomType {
  Void,
  Place
}

enum ActionType {
  None,
  North,
  Go,
  Move,
  Loot,
  Describe,
  Take,
  Kick,
  Lock,
  Unlock,
  Open
}

enum ObjectType {
  Door,
  Ball,
  Key,
  Window
}

enum CommandError {
  Boring
}
