// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum TypeKeys {
  None,
  BiomeTypes,
  TerrainTypes,
  RoomType,
  ActionType
}

enum BiomeType {
  None,
  Tundra,
  Arctic,
  Temporate,
  Alpine,
  Jungle,
  Faery
}

enum TerrainType {
  None,
  Path,
  Forest,
  Plains,
  Mud,
  DirtPath,
  Portal
}

enum RoomType {
  None,
  WoodCabin,
  Store,
  Cavern,
  StoneCabin,
  Fort,
  Room,
  Plain
}

enum DirectionType {
  None,
  North,
  South,
  East,
  West,
  Up,
  Down,
  Forward,
  Backward
}

enum DirObjectType {
  None,
  Door,
  Window,
  Stairs,
  Ladder,
  Path,
  Trail
}

enum ActionType {
  None,
  Go,
  Move,
  Loot,
  Describe,
  Take,
  Kick,
  Lock,
  Unlock,
  Open,
  Look,
  Close,
  Break,
  Throw,
  Drop,
  Inventory
}

enum ObjectType {
  None,
  Football,
  Key,
  Knife,
  Bottle
}

enum GrammarType {
  None,
  DefiniteArticle,
  Preposition,
  Adverb
}

enum MaterialType {
  None,
  Wood,
  Stone,
  Iron,
  Shit,
  IKEA,
  Flesh,
  Dirt,
  Mud,
  Glass
}

enum TxtDefType {
  None,
  DirObject,
  Dir,
  Place,
  Object,
  Action
}

enum CommandError {
  NONE,
  LEN,
  NOP,
  GONOWHERE,
  GOWHERE
}
