// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { GameMap, GameMapData, GameMapTableId } from "./tables/GameMap.sol";
import { RoomStore, RoomStoreData, RoomStoreTableId } from "./tables/RoomStore.sol";
import { ActionStore, ActionStoreTableId } from "./tables/ActionStore.sol";
import { ObjectStore, ObjectStoreData, ObjectStoreTableId } from "./tables/ObjectStore.sol";
import { TextDef, TextDefTableId } from "./tables/TextDef.sol";
import { CurrentRoomId, CurrentRoomIdTableId } from "./tables/CurrentRoomId.sol";
import { Output, OutputTableId } from "./tables/Output.sol";
