// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { TextDef, TextDefTableId } from "./tables/TextDef.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
import { History, HistoryData, HistoryTableId } from "./tables/History.sol";
