// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Dirs, DirsData, DirsTableId } from "./tables/Dirs.sol";
import { Vrbs, VrbsTableId } from "./tables/Vrbs.sol";
import { RoomStore, RoomStoreData, RoomStoreTableId } from "./tables/RoomStore.sol";
import { ActionStore, ActionStoreData, ActionStoreTableId } from "./tables/ActionStore.sol";
import { DirObjectStore, DirObjectStoreData, DirObjectStoreTableId } from "./tables/DirObjectStore.sol";
import { ObjectStore, ObjectStoreData, ObjectStoreTableId } from "./tables/ObjectStore.sol";
import { TxtDefStore, TxtDefStoreData, TxtDefStoreTableId } from "./tables/TxtDefStore.sol";
import { Output, OutputTableId } from "./tables/Output.sol";
import { CurrentPlayerId, CurrentPlayerIdTableId } from "./tables/CurrentPlayerId.sol";
import { Description, DescriptionTableId } from "./tables/Description.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
