// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICommandLookupSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICommandLookupSystem {
  function initCES() external returns (uint32);

  function setupCmds() external returns (uint32);
}
