// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IDirectionFinderSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDirectionFinderSystem {
  function initDFS(address tokeniser) external returns (address);

  function getNextRoom(string[] calldata tokens, uint32 currRm) external view returns (uint8 e, uint32 nxtRm);
}
