// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameEngineSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameEngineSystem {
  function initData() external returns (uint32);

  function enterRoom(uint32 rId) external returns (uint32 err);

  function processCommand(uint8[][] calldata tokens) external returns (uint8 err);
}
