// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameSetupSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameSetupSystem {
  function meat_GameSetupSystem_init() external returns (uint32);

  function meat_GameSetupSystem_getArrayValue(uint8 index) external view returns (uint32, uint8 er);

  function meat_GameSetupSystem_createPlace(
    uint32 id,
    uint32[] memory dirObjects,
    uint32[32] memory objects,
    bytes32 txtId
  ) external;
}
