// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameSetupSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameSetupSystem {
  function meat_GameSetupSystem_init() external returns (uint32);

  function meat_GameSetupSystem_setupCmds(uint32 cmds) external returns (uint32);
}
