// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ActionType, GrammarType, DirectionType } from "./../common.sol";

/**
 * @title ITokeniserSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITokeniserSystem {
  function initTS() external returns (address);

  function getActionType(string calldata key) external view returns (ActionType);

  function getGrammarType(string calldata key) external view returns (GrammarType);

  function getDirectionType(string calldata key) external view returns (DirectionType);
}
