// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DirectionType, MaterialType, ObjectType, ActionType, GrammarType } from "./../common.sol";

/**
 * @title ITokeniserSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITokeniserSystem {
  function meat_TokeniserSystem_initTS() external returns (address);

  function meat_TokeniserSystem_reverseDirType(DirectionType key) external view returns (string memory);

  function meat_TokeniserSystem_revMatType(MaterialType key) external view returns (string memory);

  function meat_TokeniserSystem_getObjectType(string memory key) external view returns (ObjectType);

  function meat_TokeniserSystem_getObjectNameOfObjectType(ObjectType key) external view returns (string memory);

  function meat_TokeniserSystem_getActionType(string memory key) external view returns (ActionType);

  function meat_TokeniserSystem_getGrammarType(string memory key) external view returns (GrammarType);

  function meat_TokeniserSystem_getDirectionType(string memory key) external view returns (DirectionType);
}
