// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IDirectionSystem } from "./IDirectionSystem.sol";
import { IEyeballSystem } from "./IEyeballSystem.sol";
import { IGameSetupSystem } from "./IGameSetupSystem.sol";
import { IMeatPuppetSystem } from "./IMeatPuppetSystem.sol";
import { ITokeniserSystem } from "./ITokeniserSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IDirectionSystem,
  IEyeballSystem,
  IGameSetupSystem,
  IMeatPuppetSystem,
  ITokeniserSystem
{

}
